//
//  AwarenessSummarizer.swift
//  wispr
//
//  Optional catch-up brief of what the user is being asked, generated by Apple's
//  on-device model via the shared `AppleIntelligence` service. Entirely local.
//  Strictly opportunistic: when the model is unavailable the summary is nil and
//  the awareness feature falls back to showing the last few transcript lines.
//

import Foundation

/// Generates a short catch-up brief of a meeting solicitation, when Apple's
/// on-device language model is available.
@MainActor
struct AwarenessSummarizer {

    /// Whether the on-device model can be used right now.
    static var isAvailable: Bool { AppleIntelligence.isAvailable }

    /// A human phrase for why the model is unavailable, for the Settings hint.
    static var unavailabilityReason: String? { AppleIntelligence.availability.reason }

    /// Produces a short brief of what the user is being asked, from the triggering
    /// sentence and the last few minutes of context, split into older lines
    /// (condensed, less important) and the most recent lines (verbatim, most
    /// important). Returns nil when the model is unavailable or generation fails.
    func summarize(sentence: String, speaker: String,
                   farContext: [String], recentContext: [String],
                   monitoredName: String) async -> String? {
        let instructions = """
            You help \(monitoredName), who was half-listening in a meeting and was just addressed, \
            catch up fast. Write a SHORT brief (2 to 3 sentences, under 45 words total) that covers: \
            (1) what \(monitoredName) is being asked or told, (2) the key context from the recent \
            discussion needed to understand it, and (3) if applicable, what response or action is \
            expected. Second person ("You're asked to…"). Be specific and concrete; prefer names, \
            numbers and dates from the transcript. No preamble, no bullet points, no quotes.
            """
        let far = farContext.suffix(30).joined(separator: " ")
        let recent = recentContext.joined(separator: " ")
        let prompt = """
            Earlier in the meeting (older context, least important):
            \(far.isEmpty ? "(none)" : far)

            Just before (recent context, more important):
            \(recent.isEmpty ? "(none)" : recent)

            \(speaker) then said to \(monitoredName) (most important): "\(sentence)"

            Write the short catch-up brief for \(monitoredName).
            """
        return await AppleIntelligence.generate(
            instructions: instructions, prompt: prompt, temperature: 0.3, timeout: 8)
    }
}
